# Generated by Django 3.2 on 2024-12-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0022_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/dr6m3xv0e/image/upload/v1723217421/default_profile_ztyuck.jpg', upload_to='profile_images/'),
        ),
    ]
