# Generated by Django 3.2 on 2024-12-01 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0033_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
