# Generated by Django 3.2 on 2025-01-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0037_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/hj5u1bqkt/image/upload/v1733059605/default_zkod4m.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
